#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CodeCamp.App.Droid.Resource", IsApplication=true)]

namespace CodeCamp.App.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CodeCamp.Core.Droid.Resource.String.ApplicationName = global::CodeCamp.App.Droid.Resource.String.ApplicationName;
			global::CodeCamp.Core.Droid.Resource.String.Hello = global::CodeCamp.App.Droid.Resource.String.Hello;
			global::LegacyBar.Library.Resource.Attribute.background = global::CodeCamp.App.Droid.Resource.Attribute.background;
			global::LegacyBar.Library.Resource.Attribute.background_item = global::CodeCamp.App.Droid.Resource.Attribute.background_item;
			global::LegacyBar.Library.Resource.Attribute.is_bottom = global::CodeCamp.App.Droid.Resource.Attribute.is_bottom;
			global::LegacyBar.Library.Resource.Attribute.light_icons = global::CodeCamp.App.Droid.Resource.Attribute.light_icons;
			global::LegacyBar.Library.Resource.Attribute.separator = global::CodeCamp.App.Droid.Resource.Attribute.separator;
			global::LegacyBar.Library.Resource.Attribute.theme = global::CodeCamp.App.Droid.Resource.Attribute.theme;
			global::LegacyBar.Library.Resource.Attribute.title = global::CodeCamp.App.Droid.Resource.Attribute.title;
			global::LegacyBar.Library.Resource.Attribute.title_color = global::CodeCamp.App.Droid.Resource.Attribute.title_color;
			global::LegacyBar.Library.Resource.Color.Red = global::CodeCamp.App.Droid.Resource.Color.Red;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_black = global::CodeCamp.App.Droid.Resource.Color.actionbar_accentcolor_black;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_blue = global::CodeCamp.App.Droid.Resource.Color.actionbar_accentcolor_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_darkgray = global::CodeCamp.App.Droid.Resource.Color.actionbar_accentcolor_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_lightgray = global::CodeCamp.App.Droid.Resource.Color.actionbar_accentcolor_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_background_end = global::CodeCamp.App.Droid.Resource.Color.actionbar_background_end;
			global::LegacyBar.Library.Resource.Color.actionbar_background_end_alt = global::CodeCamp.App.Droid.Resource.Color.actionbar_background_end_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end = global::CodeCamp.App.Droid.Resource.Color.actionbar_background_item_pressed_end;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end_alt = global::CodeCamp.App.Droid.Resource.Color.actionbar_background_item_pressed_end_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start = global::CodeCamp.App.Droid.Resource.Color.actionbar_background_item_pressed_start;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start_alt = global::CodeCamp.App.Droid.Resource.Color.actionbar_background_item_pressed_start_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_background_start = global::CodeCamp.App.Droid.Resource.Color.actionbar_background_start;
			global::LegacyBar.Library.Resource.Color.actionbar_background_start_alt = global::CodeCamp.App.Droid.Resource.Color.actionbar_background_start_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_black = global::CodeCamp.App.Droid.Resource.Color.actionbar_maincolor_black;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_blue = global::CodeCamp.App.Droid.Resource.Color.actionbar_maincolor_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_darkgray = global::CodeCamp.App.Droid.Resource.Color.actionbar_maincolor_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_lightgray = global::CodeCamp.App.Droid.Resource.Color.actionbar_maincolor_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_black = global::CodeCamp.App.Droid.Resource.Color.actionbar_pressedcolor_black;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_blue = global::CodeCamp.App.Droid.Resource.Color.actionbar_pressedcolor_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_darkgray = global::CodeCamp.App.Droid.Resource.Color.actionbar_pressedcolor_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_lightgray = global::CodeCamp.App.Droid.Resource.Color.actionbar_pressedcolor_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_separator = global::CodeCamp.App.Droid.Resource.Color.actionbar_separator;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_alt = global::CodeCamp.App.Droid.Resource.Color.actionbar_separator_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_black = global::CodeCamp.App.Droid.Resource.Color.actionbar_separator_black;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_blue = global::CodeCamp.App.Droid.Resource.Color.actionbar_separator_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_darkgray = global::CodeCamp.App.Droid.Resource.Color.actionbar_separator_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_lightgray = global::CodeCamp.App.Droid.Resource.Color.actionbar_separator_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_title = global::CodeCamp.App.Droid.Resource.Color.actionbar_title;
			global::LegacyBar.Library.Resource.Color.actionbar_title_alt = global::CodeCamp.App.Droid.Resource.Color.actionbar_title_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_title_black = global::CodeCamp.App.Droid.Resource.Color.actionbar_title_black;
			global::LegacyBar.Library.Resource.Color.actionbar_title_blue = global::CodeCamp.App.Droid.Resource.Color.actionbar_title_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_title_darkgray = global::CodeCamp.App.Droid.Resource.Color.actionbar_title_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_title_lightgray = global::CodeCamp.App.Droid.Resource.Color.actionbar_title_lightgray;
			global::LegacyBar.Library.Resource.Color.black = global::CodeCamp.App.Droid.Resource.Color.black;
			global::LegacyBar.Library.Resource.Color.blue = global::CodeCamp.App.Droid.Resource.Color.blue;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_end = global::CodeCamp.App.Droid.Resource.Color.bottomactionbar_background_end;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_end = global::CodeCamp.App.Droid.Resource.Color.bottomactionbar_background_item_pressed_end;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_start = global::CodeCamp.App.Droid.Resource.Color.bottomactionbar_background_item_pressed_start;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_start = global::CodeCamp.App.Droid.Resource.Color.bottomactionbar_background_start;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_black = global::CodeCamp.App.Droid.Resource.Color.bottomactionbar_maincolor_black;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_blue = global::CodeCamp.App.Droid.Resource.Color.bottomactionbar_maincolor_blue;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_darkgray = global::CodeCamp.App.Droid.Resource.Color.bottomactionbar_maincolor_darkgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_lightgray = global::CodeCamp.App.Droid.Resource.Color.bottomactionbar_maincolor_lightgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_black = global::CodeCamp.App.Droid.Resource.Color.bottomactionbar_pressedcolor_black;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_blue = global::CodeCamp.App.Droid.Resource.Color.bottomactionbar_pressedcolor_blue;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_darkgray = global::CodeCamp.App.Droid.Resource.Color.bottomactionbar_pressedcolor_darkgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_lightgray = global::CodeCamp.App.Droid.Resource.Color.bottomactionbar_pressedcolor_lightgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_separator = global::CodeCamp.App.Droid.Resource.Color.bottomactionbar_separator;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_title = global::CodeCamp.App.Droid.Resource.Color.bottomactionbar_title;
			global::LegacyBar.Library.Resource.Color.green = global::CodeCamp.App.Droid.Resource.Color.green;
			global::LegacyBar.Library.Resource.Color.grey = global::CodeCamp.App.Droid.Resource.Color.grey;
			global::LegacyBar.Library.Resource.Color.pager_black = global::CodeCamp.App.Droid.Resource.Color.pager_black;
			global::LegacyBar.Library.Resource.Color.pager_blue = global::CodeCamp.App.Droid.Resource.Color.pager_blue;
			global::LegacyBar.Library.Resource.Color.pager_darkgray = global::CodeCamp.App.Droid.Resource.Color.pager_darkgray;
			global::LegacyBar.Library.Resource.Color.pager_lightgray = global::CodeCamp.App.Droid.Resource.Color.pager_lightgray;
			global::LegacyBar.Library.Resource.Color.red = global::CodeCamp.App.Droid.Resource.Color.red;
			global::LegacyBar.Library.Resource.Color.white = global::CodeCamp.App.Droid.Resource.Color.white;
			global::LegacyBar.Library.Resource.Color.yellow = global::CodeCamp.App.Droid.Resource.Color.yellow;
			global::LegacyBar.Library.Resource.Dimension.actionbar_accentheight = global::CodeCamp.App.Droid.Resource.Dimension.actionbar_accentheight;
			global::LegacyBar.Library.Resource.Dimension.actionbar_height = global::CodeCamp.App.Droid.Resource.Dimension.actionbar_height;
			global::LegacyBar.Library.Resource.Dimension.actionbar_home_item_width = global::CodeCamp.App.Droid.Resource.Dimension.actionbar_home_item_width;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_height = global::CodeCamp.App.Droid.Resource.Dimension.actionbar_item_height;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_height_over = global::CodeCamp.App.Droid.Resource.Dimension.actionbar_item_height_over;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_height_overflow = global::CodeCamp.App.Droid.Resource.Dimension.actionbar_item_height_overflow;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_width = global::CodeCamp.App.Droid.Resource.Dimension.actionbar_item_width;
			global::LegacyBar.Library.Resource.Drawable.actionbar_back_indicator = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_back_indicator;
			global::LegacyBar.Library.Resource.Drawable.actionbar_back_indicator_dark = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_back_indicator_dark;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_background;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_alt = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_background_alt;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_black = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_background_black;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_blue = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_background_blue;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_darkgray = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_background_darkgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_lightgray = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_background_lightgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_btn;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_alt = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_btn_alt;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_black = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_btn_black;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_blue = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_btn_blue;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_darkgray = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_btn_darkgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_lightgray = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_btn_lightgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_normal = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_btn_normal;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_normal_alt = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_btn_normal_alt;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_btn_pressed;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed_alt = global::CodeCamp.App.Droid.Resource.Drawable.actionbar_btn_pressed_alt;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background = global::CodeCamp.App.Droid.Resource.Drawable.bottomactionbar_background;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_black = global::CodeCamp.App.Droid.Resource.Drawable.bottomactionbar_background_black;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_blue = global::CodeCamp.App.Droid.Resource.Drawable.bottomactionbar_background_blue;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_darkgray = global::CodeCamp.App.Droid.Resource.Drawable.bottomactionbar_background_darkgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_lightgray = global::CodeCamp.App.Droid.Resource.Drawable.bottomactionbar_background_lightgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn = global::CodeCamp.App.Droid.Resource.Drawable.bottomactionbar_btn;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_black = global::CodeCamp.App.Droid.Resource.Drawable.bottomactionbar_btn_black;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_blue = global::CodeCamp.App.Droid.Resource.Drawable.bottomactionbar_btn_blue;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_darkgray = global::CodeCamp.App.Droid.Resource.Drawable.bottomactionbar_btn_darkgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_lightgray = global::CodeCamp.App.Droid.Resource.Drawable.bottomactionbar_btn_lightgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_normal = global::CodeCamp.App.Droid.Resource.Drawable.bottomactionbar_btn_normal;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_pressed = global::CodeCamp.App.Droid.Resource.Drawable.bottomactionbar_btn_pressed;
			global::LegacyBar.Library.Resource.Drawable.dropdown_btn_holo_dark = global::CodeCamp.App.Droid.Resource.Drawable.dropdown_btn_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_btn_holo_light = global::CodeCamp.App.Droid.Resource.Drawable.dropdown_btn_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_disabled_holo_dark = global::CodeCamp.App.Droid.Resource.Drawable.dropdown_disabled_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_disabled_holo_light = global::CodeCamp.App.Droid.Resource.Drawable.dropdown_disabled_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_focused_holo_dark = global::CodeCamp.App.Droid.Resource.Drawable.dropdown_focused_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_focused_holo_light = global::CodeCamp.App.Droid.Resource.Drawable.dropdown_focused_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_normal_holo_dark = global::CodeCamp.App.Droid.Resource.Drawable.dropdown_normal_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_normal_holo_light = global::CodeCamp.App.Droid.Resource.Drawable.dropdown_normal_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_pressed_holo_dark = global::CodeCamp.App.Droid.Resource.Drawable.dropdown_pressed_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_pressed_holo_light = global::CodeCamp.App.Droid.Resource.Drawable.dropdown_pressed_holo_light;
			global::LegacyBar.Library.Resource.Drawable.ic_action_overflow = global::CodeCamp.App.Droid.Resource.Drawable.ic_action_overflow;
			global::LegacyBar.Library.Resource.Drawable.ic_action_overflow_dark = global::CodeCamp.App.Droid.Resource.Drawable.ic_action_overflow_dark;
			global::LegacyBar.Library.Resource.Id.actionbar_actions = global::CodeCamp.App.Droid.Resource.Id.actionbar_actions;
			global::LegacyBar.Library.Resource.Id.actionbar_home = global::CodeCamp.App.Droid.Resource.Id.actionbar_home;
			global::LegacyBar.Library.Resource.Id.actionbar_home_bg = global::CodeCamp.App.Droid.Resource.Id.actionbar_home_bg;
			global::LegacyBar.Library.Resource.Id.actionbar_home_btn = global::CodeCamp.App.Droid.Resource.Id.actionbar_home_btn;
			global::LegacyBar.Library.Resource.Id.actionbar_home_is_back = global::CodeCamp.App.Droid.Resource.Id.actionbar_home_is_back;
			global::LegacyBar.Library.Resource.Id.actionbar_home_logo = global::CodeCamp.App.Droid.Resource.Id.actionbar_home_logo;
			global::LegacyBar.Library.Resource.Id.actionbar_item = global::CodeCamp.App.Droid.Resource.Id.actionbar_item;
			global::LegacyBar.Library.Resource.Id.actionbar_progress = global::CodeCamp.App.Droid.Resource.Id.actionbar_progress;
			global::LegacyBar.Library.Resource.Id.actionbar_spinner = global::CodeCamp.App.Droid.Resource.Id.actionbar_spinner;
			global::LegacyBar.Library.Resource.Id.actionbar_title = global::CodeCamp.App.Droid.Resource.Id.actionbar_title;
			global::LegacyBar.Library.Resource.Id.actionbar_title_layout = global::CodeCamp.App.Droid.Resource.Id.actionbar_title_layout;
			global::LegacyBar.Library.Resource.Id.custom = global::CodeCamp.App.Droid.Resource.Id.custom;
			global::LegacyBar.Library.Resource.Id.holo_black = global::CodeCamp.App.Droid.Resource.Id.holo_black;
			global::LegacyBar.Library.Resource.Id.holo_blue = global::CodeCamp.App.Droid.Resource.Id.holo_blue;
			global::LegacyBar.Library.Resource.Id.holo_gray = global::CodeCamp.App.Droid.Resource.Id.holo_gray;
			global::LegacyBar.Library.Resource.Id.holo_light = global::CodeCamp.App.Droid.Resource.Id.holo_light;
			global::LegacyBar.Library.Resource.Id.overflow_spinner = global::CodeCamp.App.Droid.Resource.Id.overflow_spinner;
			global::LegacyBar.Library.Resource.Id.screen = global::CodeCamp.App.Droid.Resource.Id.screen;
			global::LegacyBar.Library.Resource.Layout.actionbar = global::CodeCamp.App.Droid.Resource.Layout.actionbar;
			global::LegacyBar.Library.Resource.Layout.actionbar_item = global::CodeCamp.App.Droid.Resource.Layout.actionbar_item;
			global::LegacyBar.Library.Resource.Layout.blankspinner = global::CodeCamp.App.Droid.Resource.Layout.blankspinner;
			global::LegacyBar.Library.Resource.Layout.overflowactionbar_item = global::CodeCamp.App.Droid.Resource.Layout.overflowactionbar_item;
			global::LegacyBar.Library.Resource.Layout.spinneritem = global::CodeCamp.App.Droid.Resource.Layout.spinneritem;
			global::LegacyBar.Library.Resource.String.actionbar_activity_not_found = global::CodeCamp.App.Droid.Resource.String.actionbar_activity_not_found;
			global::LegacyBar.Library.Resource.Style.actionbar = global::CodeCamp.App.Droid.Resource.Style.actionbar;
			global::LegacyBar.Library.Resource.Style.actionbarhomeitem = global::CodeCamp.App.Droid.Resource.Style.actionbarhomeitem;
			global::LegacyBar.Library.Resource.Style.actionbarhomelogo = global::CodeCamp.App.Droid.Resource.Style.actionbarhomelogo;
			global::LegacyBar.Library.Resource.Style.actionbaritem = global::CodeCamp.App.Droid.Resource.Style.actionbaritem;
			global::LegacyBar.Library.Resource.Style.actionbarprogressbar = global::CodeCamp.App.Droid.Resource.Style.actionbarprogressbar;
			global::LegacyBar.Library.Resource.Style.clearbutton = global::CodeCamp.App.Droid.Resource.Style.clearbutton;
			global::LegacyBar.Library.Resource.Styleable.actionbar = global::CodeCamp.App.Droid.Resource.Styleable.actionbar;
			global::LegacyBar.Library.Resource.Styleable.actionbar_background = global::CodeCamp.App.Droid.Resource.Styleable.actionbar_background;
			global::LegacyBar.Library.Resource.Styleable.actionbar_background_item = global::CodeCamp.App.Droid.Resource.Styleable.actionbar_background_item;
			global::LegacyBar.Library.Resource.Styleable.actionbar_is_bottom = global::CodeCamp.App.Droid.Resource.Styleable.actionbar_is_bottom;
			global::LegacyBar.Library.Resource.Styleable.actionbar_light_icons = global::CodeCamp.App.Droid.Resource.Styleable.actionbar_light_icons;
			global::LegacyBar.Library.Resource.Styleable.actionbar_separator = global::CodeCamp.App.Droid.Resource.Styleable.actionbar_separator;
			global::LegacyBar.Library.Resource.Styleable.actionbar_theme = global::CodeCamp.App.Droid.Resource.Styleable.actionbar_theme;
			global::LegacyBar.Library.Resource.Styleable.actionbar_title = global::CodeCamp.App.Droid.Resource.Styleable.actionbar_title;
			global::LegacyBar.Library.Resource.Styleable.actionbar_title_color = global::CodeCamp.App.Droid.Resource.Styleable.actionbar_title_color;
			global::SlidingMenuSharp.Resource.Attribute.behindOffset = global::CodeCamp.App.Droid.Resource.Attribute.behindOffset;
			global::SlidingMenuSharp.Resource.Attribute.behindScrollScale = global::CodeCamp.App.Droid.Resource.Attribute.behindScrollScale;
			global::SlidingMenuSharp.Resource.Attribute.behindWidth = global::CodeCamp.App.Droid.Resource.Attribute.behindWidth;
			global::SlidingMenuSharp.Resource.Attribute.fadeDegree = global::CodeCamp.App.Droid.Resource.Attribute.fadeDegree;
			global::SlidingMenuSharp.Resource.Attribute.fadeEnabled = global::CodeCamp.App.Droid.Resource.Attribute.fadeEnabled;
			global::SlidingMenuSharp.Resource.Attribute.mode = global::CodeCamp.App.Droid.Resource.Attribute.mode;
			global::SlidingMenuSharp.Resource.Attribute.selectorDrawable = global::CodeCamp.App.Droid.Resource.Attribute.selectorDrawable;
			global::SlidingMenuSharp.Resource.Attribute.selectorEnabled = global::CodeCamp.App.Droid.Resource.Attribute.selectorEnabled;
			global::SlidingMenuSharp.Resource.Attribute.shadowDrawable = global::CodeCamp.App.Droid.Resource.Attribute.shadowDrawable;
			global::SlidingMenuSharp.Resource.Attribute.shadowWidth = global::CodeCamp.App.Droid.Resource.Attribute.shadowWidth;
			global::SlidingMenuSharp.Resource.Attribute.touchModeAbove = global::CodeCamp.App.Droid.Resource.Attribute.touchModeAbove;
			global::SlidingMenuSharp.Resource.Attribute.touchModeBehind = global::CodeCamp.App.Droid.Resource.Attribute.touchModeBehind;
			global::SlidingMenuSharp.Resource.Attribute.viewAbove = global::CodeCamp.App.Droid.Resource.Attribute.viewAbove;
			global::SlidingMenuSharp.Resource.Attribute.viewBehind = global::CodeCamp.App.Droid.Resource.Attribute.viewBehind;
			global::SlidingMenuSharp.Resource.Id.fullscreen = global::CodeCamp.App.Droid.Resource.Id.fullscreen;
			global::SlidingMenuSharp.Resource.Id.left = global::CodeCamp.App.Droid.Resource.Id.left;
			global::SlidingMenuSharp.Resource.Id.margin = global::CodeCamp.App.Droid.Resource.Id.margin;
			global::SlidingMenuSharp.Resource.Id.right = global::CodeCamp.App.Droid.Resource.Id.right;
			global::SlidingMenuSharp.Resource.Id.selected_view = global::CodeCamp.App.Droid.Resource.Id.selected_view;
			global::SlidingMenuSharp.Resource.Id.slidingmenumain = global::CodeCamp.App.Droid.Resource.Id.slidingmenumain;
			global::SlidingMenuSharp.Resource.Layout.slidingmenumain = global::CodeCamp.App.Droid.Resource.Layout.slidingmenumain;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu = global::CodeCamp.App.Droid.Resource.Styleable.SlidingMenu;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindOffset = global::CodeCamp.App.Droid.Resource.Styleable.SlidingMenu_behindOffset;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindScrollScale = global::CodeCamp.App.Droid.Resource.Styleable.SlidingMenu_behindScrollScale;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindWidth = global::CodeCamp.App.Droid.Resource.Styleable.SlidingMenu_behindWidth;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeDegree = global::CodeCamp.App.Droid.Resource.Styleable.SlidingMenu_fadeDegree;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeEnabled = global::CodeCamp.App.Droid.Resource.Styleable.SlidingMenu_fadeEnabled;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_mode = global::CodeCamp.App.Droid.Resource.Styleable.SlidingMenu_mode;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorDrawable = global::CodeCamp.App.Droid.Resource.Styleable.SlidingMenu_selectorDrawable;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorEnabled = global::CodeCamp.App.Droid.Resource.Styleable.SlidingMenu_selectorEnabled;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowDrawable = global::CodeCamp.App.Droid.Resource.Styleable.SlidingMenu_shadowDrawable;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowWidth = global::CodeCamp.App.Droid.Resource.Styleable.SlidingMenu_shadowWidth;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeAbove = global::CodeCamp.App.Droid.Resource.Styleable.SlidingMenu_touchModeAbove;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeBehind = global::CodeCamp.App.Droid.Resource.Styleable.SlidingMenu_touchModeBehind;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewAbove = global::CodeCamp.App.Droid.Resource.Styleable.SlidingMenu_viewAbove;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewBehind = global::CodeCamp.App.Droid.Resource.Styleable.SlidingMenu_viewBehind;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010016
			public const int MvxBind = 2130771990;
			
			// aapt resource value: 0x7f010018
			public const int MvxDropDownItemTemplate = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int MvxItemTemplate = 2130771991;
			
			// aapt resource value: 0x7f010019
			public const int MvxSource = 2130771993;
			
			// aapt resource value: 0x7f010011
			public const int background = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int background_item = 2130771986;
			
			// aapt resource value: 0x7f010003
			public const int behindOffset = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int behindScrollScale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int behindWidth = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int fadeDegree = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int fadeEnabled = 2130771978;
			
			// aapt resource value: 0x7f010014
			public const int is_bottom = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int light_icons = 2130771989;
			
			// aapt resource value: 0x7f010000
			public const int mode = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public const int selectorDrawable = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int selectorEnabled = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int separator = 2130771984;
			
			// aapt resource value: 0x7f010008
			public const int shadowDrawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int shadowWidth = 2130771977;
			
			// aapt resource value: 0x7f010013
			public const int theme = 2130771987;
			
			// aapt resource value: 0x7f01000e
			public const int title = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int title_color = 2130771983;
			
			// aapt resource value: 0x7f010006
			public const int touchModeAbove = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int touchModeBehind = 2130771975;
			
			// aapt resource value: 0x7f010001
			public const int viewAbove = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int viewBehind = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050039
			public const int Red = 2131034169;
			
			// aapt resource value: 0x7f050023
			public const int actionbar_accentcolor_black = 2131034147;
			
			// aapt resource value: 0x7f05002b
			public const int actionbar_accentcolor_blue = 2131034155;
			
			// aapt resource value: 0x7f05001b
			public const int actionbar_accentcolor_darkgray = 2131034139;
			
			// aapt resource value: 0x7f050013
			public const int actionbar_accentcolor_lightgray = 2131034131;
			
			// aapt resource value: 0x7f050003
			public const int actionbar_background_end = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int actionbar_background_end_alt = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int actionbar_background_item_pressed_end = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int actionbar_background_item_pressed_end_alt = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int actionbar_background_item_pressed_start = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int actionbar_background_item_pressed_start_alt = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int actionbar_background_start = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int actionbar_background_start_alt = 2131034120;
			
			// aapt resource value: 0x7f050022
			public const int actionbar_maincolor_black = 2131034146;
			
			// aapt resource value: 0x7f05002a
			public const int actionbar_maincolor_blue = 2131034154;
			
			// aapt resource value: 0x7f05001a
			public const int actionbar_maincolor_darkgray = 2131034138;
			
			// aapt resource value: 0x7f050012
			public const int actionbar_maincolor_lightgray = 2131034130;
			
			// aapt resource value: 0x7f050024
			public const int actionbar_pressedcolor_black = 2131034148;
			
			// aapt resource value: 0x7f05002c
			public const int actionbar_pressedcolor_blue = 2131034156;
			
			// aapt resource value: 0x7f05001c
			public const int actionbar_pressedcolor_darkgray = 2131034140;
			
			// aapt resource value: 0x7f050014
			public const int actionbar_pressedcolor_lightgray = 2131034132;
			
			// aapt resource value: 0x7f050000
			public const int actionbar_separator = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int actionbar_separator_alt = 2131034118;
			
			// aapt resource value: 0x7f050026
			public const int actionbar_separator_black = 2131034150;
			
			// aapt resource value: 0x7f05002e
			public const int actionbar_separator_blue = 2131034158;
			
			// aapt resource value: 0x7f05001e
			public const int actionbar_separator_darkgray = 2131034142;
			
			// aapt resource value: 0x7f050016
			public const int actionbar_separator_lightgray = 2131034134;
			
			// aapt resource value: 0x7f050001
			public const int actionbar_title = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int actionbar_title_alt = 2131034119;
			
			// aapt resource value: 0x7f050025
			public const int actionbar_title_black = 2131034149;
			
			// aapt resource value: 0x7f05002d
			public const int actionbar_title_blue = 2131034157;
			
			// aapt resource value: 0x7f05001d
			public const int actionbar_title_darkgray = 2131034141;
			
			// aapt resource value: 0x7f050015
			public const int actionbar_title_lightgray = 2131034133;
			
			// aapt resource value: 0x7f050033
			public const int black = 2131034163;
			
			// aapt resource value: 0x7f050036
			public const int blue = 2131034166;
			
			// aapt resource value: 0x7f05000f
			public const int bottomactionbar_background_end = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int bottomactionbar_background_item_pressed_end = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int bottomactionbar_background_item_pressed_start = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int bottomactionbar_background_start = 2131034126;
			
			// aapt resource value: 0x7f050027
			public const int bottomactionbar_maincolor_black = 2131034151;
			
			// aapt resource value: 0x7f05002f
			public const int bottomactionbar_maincolor_blue = 2131034159;
			
			// aapt resource value: 0x7f05001f
			public const int bottomactionbar_maincolor_darkgray = 2131034143;
			
			// aapt resource value: 0x7f050017
			public const int bottomactionbar_maincolor_lightgray = 2131034135;
			
			// aapt resource value: 0x7f050028
			public const int bottomactionbar_pressedcolor_black = 2131034152;
			
			// aapt resource value: 0x7f050030
			public const int bottomactionbar_pressedcolor_blue = 2131034160;
			
			// aapt resource value: 0x7f050020
			public const int bottomactionbar_pressedcolor_darkgray = 2131034144;
			
			// aapt resource value: 0x7f050018
			public const int bottomactionbar_pressedcolor_lightgray = 2131034136;
			
			// aapt resource value: 0x7f05000c
			public const int bottomactionbar_separator = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int bottomactionbar_title = 2131034125;
			
			// aapt resource value: 0x7f050034
			public const int green = 2131034164;
			
			// aapt resource value: 0x7f050037
			public const int grey = 2131034167;
			
			// aapt resource value: 0x7f050029
			public const int pager_black = 2131034153;
			
			// aapt resource value: 0x7f050031
			public const int pager_blue = 2131034161;
			
			// aapt resource value: 0x7f050021
			public const int pager_darkgray = 2131034145;
			
			// aapt resource value: 0x7f050019
			public const int pager_lightgray = 2131034137;
			
			// aapt resource value: 0x7f050035
			public const int red = 2131034165;
			
			// aapt resource value: 0x7f050032
			public const int white = 2131034162;
			
			// aapt resource value: 0x7f050038
			public const int yellow = 2131034168;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int actionbar_accentheight = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int actionbar_height = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int actionbar_home_item_width = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int actionbar_item_height = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int actionbar_item_height_over = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int actionbar_item_height_overflow = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int actionbar_item_width = 2131099652;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_back_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar_back_indicator_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionbar_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar_background_alt = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar_background_black = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int actionbar_background_blue = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int actionbar_background_darkgray = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int actionbar_background_lightgray = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int actionbar_btn = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int actionbar_btn_alt = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int actionbar_btn_black = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int actionbar_btn_blue = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int actionbar_btn_darkgray = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int actionbar_btn_lightgray = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int actionbar_btn_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int actionbar_btn_normal_alt = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int actionbar_btn_pressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int actionbar_btn_pressed_alt = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bottomactionbar_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int bottomactionbar_background_black = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bottomactionbar_background_blue = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bottomactionbar_background_darkgray = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int bottomactionbar_background_lightgray = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bottomactionbar_btn = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int bottomactionbar_btn_black = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int bottomactionbar_btn_blue = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int bottomactionbar_btn_darkgray = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int bottomactionbar_btn_lightgray = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int bottomactionbar_btn_normal = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int bottomactionbar_btn_pressed = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Calendar = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int dropdown_btn_holo_dark = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int dropdown_btn_holo_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int dropdown_disabled_holo_dark = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int dropdown_disabled_holo_light = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int dropdown_focused_holo_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int dropdown_focused_holo_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int dropdown_normal_holo_dark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int dropdown_normal_holo_light = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int dropdown_pressed_holo_dark = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int dropdown_pressed_holo_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Email = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_action_overflow = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_action_overflow_dark = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Icon = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Link = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Menu = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Refresh = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int SlidingMenuShadow = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int SlidingMenuShadowRight = 2130837553;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04001f
			public const int Abstract = 2130968607;
			
			// aapt resource value: 0x7f040017
			public const int ActionBar = 2130968599;
			
			// aapt resource value: 0x7f040023
			public const int Description = 2130968611;
			
			// aapt resource value: 0x7f040020
			public const int HeaderText = 2130968608;
			
			// aapt resource value: 0x7f040018
			public const int Map = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int MenuFrame = 2130968601;
			
			// aapt resource value: 0x7f04000a
			public const int MvxBindingTagUnique = 2130968586;
			
			// aapt resource value: 0x7f040022
			public const int Name = 2130968610;
			
			// aapt resource value: 0x7f040025
			public const int Refresh = 2130968613;
			
			// aapt resource value: 0x7f04001d
			public const int Room = 2130968605;
			
			// aapt resource value: 0x7f04001b
			public const int SessionList = 2130968603;
			
			// aapt resource value: 0x7f04001e
			public const int Speaker = 2130968606;
			
			// aapt resource value: 0x7f040024
			public const int SponsorList = 2130968612;
			
			// aapt resource value: 0x7f04001c
			public const int Title = 2130968604;
			
			// aapt resource value: 0x7f040011
			public const int actionbar_actions = 2130968593;
			
			// aapt resource value: 0x7f04000c
			public const int actionbar_home = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int actionbar_home_bg = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int actionbar_home_btn = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int actionbar_home_is_back = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int actionbar_home_logo = 2130968589;
			
			// aapt resource value: 0x7f040016
			public const int actionbar_item = 2130968598;
			
			// aapt resource value: 0x7f040013
			public const int actionbar_progress = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int actionbar_spinner = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int actionbar_title = 2130968596;
			
			// aapt resource value: 0x7f040012
			public const int actionbar_title_layout = 2130968594;
			
			// aapt resource value: 0x7f040005
			public const int custom = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int fullscreen = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int holo_black = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int holo_blue = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int holo_gray = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int holo_light = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int left = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int margin = 2130968578;
			
			// aapt resource value: 0x7f04001a
			public const int overflow_spinner = 2130968602;
			
			// aapt resource value: 0x7f040001
			public const int right = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int screen = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int selected_view = 2130968580;
			
			// aapt resource value: 0x7f040021
			public const int slidingmenumain = 2130968609;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionbar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int actionbar_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int blankspinner = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Map = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Menu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MenuFrame = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int overflowactionbar_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Overview = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Session = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SessionListHeader = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SessionListItem = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Sessions = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int slidingmenumain = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Speaker = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SpeakerListItem = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Speakers = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int spinneritem = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Sponsor = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int SponsorListHeader = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int SponsorListItem = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Sponsors = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int RefreshMenu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070002
			public const int ApplicationName = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int Hello = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int actionbar_activity_not_found = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int actionbar = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int actionbarhomeitem = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int actionbarhomelogo = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int actionbaritem = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int actionbarprogressbar = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int clearbutton = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771990};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771993};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771991,
					2130771992};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] SlidingMenu = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 3
			public const int SlidingMenu_behindOffset = 3;
			
			// aapt resource value: 5
			public const int SlidingMenu_behindScrollScale = 5;
			
			// aapt resource value: 4
			public const int SlidingMenu_behindWidth = 4;
			
			// aapt resource value: 11
			public const int SlidingMenu_fadeDegree = 11;
			
			// aapt resource value: 10
			public const int SlidingMenu_fadeEnabled = 10;
			
			// aapt resource value: 0
			public const int SlidingMenu_mode = 0;
			
			// aapt resource value: 13
			public const int SlidingMenu_selectorDrawable = 13;
			
			// aapt resource value: 12
			public const int SlidingMenu_selectorEnabled = 12;
			
			// aapt resource value: 8
			public const int SlidingMenu_shadowDrawable = 8;
			
			// aapt resource value: 9
			public const int SlidingMenu_shadowWidth = 9;
			
			// aapt resource value: 6
			public const int SlidingMenu_touchModeAbove = 6;
			
			// aapt resource value: 7
			public const int SlidingMenu_touchModeBehind = 7;
			
			// aapt resource value: 1
			public const int SlidingMenu_viewAbove = 1;
			
			// aapt resource value: 2
			public const int SlidingMenu_viewBehind = 2;
			
			public static int[] actionbar = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989};
			
			// aapt resource value: 3
			public const int actionbar_background = 3;
			
			// aapt resource value: 4
			public const int actionbar_background_item = 4;
			
			// aapt resource value: 6
			public const int actionbar_is_bottom = 6;
			
			// aapt resource value: 7
			public const int actionbar_light_icons = 7;
			
			// aapt resource value: 2
			public const int actionbar_separator = 2;
			
			// aapt resource value: 5
			public const int actionbar_theme = 5;
			
			// aapt resource value: 0
			public const int actionbar_title = 0;
			
			// aapt resource value: 1
			public const int actionbar_title_color = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
